### ISSUE TITLE
Use PSR-2 code style

### ISSUE THREAD

**Issue by shadowhand** [SeinopSys/oauth2-deviantart#1]
I find it a little weird that this package doesn't use [PSR-2](http://www.php-fig.org/psr/psr-2/) code style. There are a number of whitespace issues as well.

**Comment by shadowhand** [comment]
It's also not necessary to duplicate all the comments from AbstractProvider. The parent class method docblocks will automatically be applied by IDEs.

**Comment by SeinopSys** [comment]
Thank you for the heads up. I've made some changes to address these concerns, and I'd appreciate if you could give `v1.0.1` a second look & report back if it's all good now.
